"""
Django settings for crm project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-9&d3qk!2o2zozr#fgwsad4018g5ckl)2qiu)y%z)^)!+gt$uwj'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['.vercel.app']


# Application definition

INSTALLED_APPS = [
    'jazzmin',         # must come before 'django.contrib.admin'
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'accounts',
    'ckeditor',
    'rest_framework',
    'import_export'

]
try:
    latest_logo = AdminLogo.objects.latest('id')
    site_logo_path = f"admin_logo/{latest_logo.image.name.split('/')[-1]}"
except:
    site_logo_path = "img/default_logo.png"  # fallback


JAZZMIN_SETTINGS = {
    "site_logo": "img/download.png",
    "site_title": "My Project Admin",
    "site_header": "My Admin Dashboard",
    "welcome_sign": "Welcome to My Admin",
    "copyright": "My Company",
    "search_model": "auth.User",
    "show_sidebar": True,
    "navigation_expanded": True,
    "icons": {
        "auth.User": "fas fa-user",
        "auth.Group": "fas fa-users",
        "accounts.Product": "fas fa-boxes",
        "accounts.Category": "fas fa-tags",
        "accounts.TblInfor": "fas fa-info-circle",
        "accounts.TblBannerHome": "fas fa-home",
        "accounts.TblBannerall": "fas fa-images",
        "accounts.TblBanneral1": "fas fa-image",
        "accounts.TblMenu": "fas fa-bars",
        "accounts.TblMenuDetail": "fas fa-list-ul",
        "accounts.TblAbout": "fas fa-address-card",
        "accounts.ProductDetail": "fas fa-search-plus",
        "accounts.TblNew": "fas fa-newspaper",
        "accounts.TblContent": "fas fa-file-alt",
        "accounts.TblNewDetail": "fas fa-file-alt",
        "accounts.TblOurTeam": "fas fa-users-cog",
        "accounts.TblContact": "fas fa-address-book",
        "accounts.footer": "fas fa-window-maximize",
        "accounts.TblTags": "fas fa-tags",
        "accounts.TblRecent_Posts": "fas fa-history",
        "accounts.TblNewone": "fas fa-newspaper",
        "accounts.BillingDetail": "fas fa-file-invoice-dollar",
        "accounts.CartItem": "fas fa-shopping-cart",
        "accounts.TblComments": "fas fa-comment-dots",
        "accounts.AccessToken": "fas fa-key",
        
    }
}






REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ],
     'DEFAULT_PERMISSION_CLASSES': ['rest_framework.permissions.AllowAny'],
}



CKEDITOR_UPLOAD_PATH = "uploads/"
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


STATIC_URL = 'static/'

STATICFILES_DIRS =[
    BASE_DIR / 'static/',
]

MEDIA_URL = '/'

MEDIA_ROOT = Path(BASE_DIR) / 'static/'


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'crm.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'crm.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

ALLOWED_HOSTS = ['127.0.0.1', 'localhost', 'phonrithya.pythonanywhere.com']


